<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression></PropertyGroup><ItemGroup><ProjectReference Include="../Jourfold.Application/Jourfold.Application.csproj"/><PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9"/><PackageReference Include="PDFsharp" Version="6.2.4"/><PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3"/></ItemGroup></Project>
