#!/usr/bin/env python3
"""Convert the canonical brand SVGs into Avalonia DrawingImage resources.

Usage: python3 eng/brand.py assets/branding src/Jourfold.Desktop/Theme/Brand.axaml

The SVG files stay canonical. This generates vector drawings so the application renders the
mark and wordmark sharply at every scale without an SVG runtime or the Outfit font.
"""
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from icons import normalize_path, fmt  # noqa: E402


def parse_transform(text: str):
    matrix = (1.0, 0.0, 0.0, 1.0, 0.0, 0.0)
    for part in text.replace(",", " ").split(")"):
        part = part.strip()
        if not part:
            continue
        name, args = part.split("(")
        values = [float(v) for v in args.split()]
        name = name.strip()
        if name == "translate":
            m = (1, 0, 0, 1, values[0], values[1] if len(values) > 1 else 0)
        elif name == "scale":
            m = (values[0], 0, 0, values[1] if len(values) > 1 else values[0], 0, 0)
        else:
            raise ValueError(name)
        matrix = multiply(matrix, m)
    return matrix


def multiply(a, b):
    """Return the matrix that applies b first, then a (SVG nesting order)."""
    a1, b1, c1, d1, e1, f1 = a
    a2, b2, c2, d2, e2, f2 = b
    return (a1 * a2 + c1 * b2, b1 * a2 + d1 * b2, a1 * c2 + c1 * d2, b1 * c2 + d1 * d2, a1 * e2 + c1 * f2 + e1, b1 * e2 + d1 * f2 + f1)


def apply(data: str, m) -> str:
    """Apply an affine matrix to an absolute path (M, L, H, V, Q, C, Z) and return the new path data."""
    a, b, c, d, e, f = m
    tokens = data.split()
    out = []
    i = 0
    x = y = 0.0
    def point(px, py):
        return fmt(a * px + c * py + e) + " " + fmt(b * px + d * py + f)
    while i < len(tokens):
        cmd = tokens[i]
        i += 1
        if cmd in ("F0", "F1"):
            out.append(cmd)
            continue
        if cmd.islower() and cmd != "z":
            raise ValueError("relative commands are not supported in brand paths")
        if cmd in ("Z", "z"):
            out.append("Z")
            continue
        if cmd == "H":
            x = float(tokens[i]); i += 1; out.append("L " + point(x, y)); continue
        if cmd == "V":
            y = float(tokens[i]); i += 1; out.append("L " + point(x, y)); continue
        count = {"M": 1, "L": 1, "Q": 2, "C": 3}[cmd]
        pts = []
        for _ in range(count):
            px, py = float(tokens[i]), float(tokens[i + 1]); i += 2
            pts.append(point(px, py))
            x, y = px, py
        out.append(cmd + " " + " ".join(pts))
    return " ".join(out)


def drawings(element, matrix, fill, out):
    tag = element.tag.split("}")[-1]
    if "transform" in element.attrib:
        matrix = multiply(matrix, parse_transform(element.attrib["transform"]))
    fill = element.attrib.get("fill", fill)
    if tag == "path":
        data = normalize_path(element.attrib["d"])
        prefix = "F0 " if element.attrib.get("fill-rule") == "evenodd" else "F1 "
        out.append((fill, prefix + data, matrix))
    for child in element:
        drawings(child, matrix, fill, out)


def drawing_image(key: str, svg: Path, recolor=None) -> list:
    root = ET.parse(svg).getroot()
    x, y, w, h = (float(v) for v in root.attrib["viewBox"].split())
    out = []
    drawings(root, (1, 0, 0, 1, -x, -y), "#000", out)
    lines = [f'  <DrawingImage x:Key="{key}">', "    <DrawingGroup>",
             f'      <GeometryDrawing Brush="Transparent" Geometry="M 0 0 H {fmt(w)} V {fmt(h)} H 0 Z"/>']
    for fill, data, m in out:
        color = (recolor or {}).get(fill.lower(), fill)
        if m != (1, 0, 0, 1, 0, 0):
            data = apply(data, m)
        lines.append(f'      <GeometryDrawing Brush="{color}">')
        lines.append(f"        <GeometryDrawing.Geometry><StreamGeometry>{data}</StreamGeometry></GeometryDrawing.Geometry>")
        lines.append("      </GeometryDrawing>")
    lines += ["    </DrawingGroup>", "  </DrawingImage>"]
    return lines


def main(source: str, target: str) -> None:
    src = Path(source)
    lines = [
        "<!-- Generated by eng/brand.py from assets/branding/*.svg. Edit the SVG sources, not this file. -->",
        '<ResourceDictionary xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">',
    ]
    lines += drawing_image("Brand.Mark", src / "mark.svg")
    lines += drawing_image("Brand.Lockup.Light", src / "lockup.svg")
    lines += drawing_image("Brand.Lockup.Dark", src / "lockup-dark.svg")
    lines.append("</ResourceDictionary>")
    Path(target).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(target)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
