#!/usr/bin/env python3
"""Convert the canonical brand SVGs into Avalonia DrawingImage resources.

Usage: python3 eng/brand.py assets/branding src/Jourfold.Desktop/Theme/Brand.axaml

The SVG files stay canonical. This generates vector drawings so the application renders the
mark and wordmark sharply at every scale without an SVG runtime or the Outfit font.
"""
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from icons import normalize_path, fmt  # noqa: E402


def parse_transform(text: str):
    matrix = (1.0, 0.0, 0.0, 1.0, 0.0, 0.0)
    for part in text.replace(",", " ").split(")"):
        part = part.strip()
        if not part:
            continue
        name, args = part.split("(")
        values = [float(v) for v in args.split()]
        name = name.strip()
        if name == "translate":
            m = (1, 0, 0, 1, values[0], values[1] if len(values) > 1 else 0)
        elif name == "scale":
            m = (values[0], 0, 0, values[1] if len(values) > 1 else values[0], 0, 0)
        else:
            raise ValueError(name)
        matrix = multiply(matrix, m)
    return matrix


def multiply(a, b):
    """Return the matrix that applies b first, then a (SVG nesting order)."""
    a1, b1, c1, d1, e1, f1 = a
    a2, b2, c2, d2, e2, f2 = b
    return (a1 * a2 + c1 * b2, b1 * a2 + d1 * b2, a1 * c2 + c1 * d2, b1 * c2 + d1 * d2, a1 * e2 + c1 * f2 + e1, b1 * e2 + d1 * f2 + f1)


def drawings(element, matrix, fill, out):
    tag = element.tag.split("}")[-1]
    if "transform" in element.attrib:
        matrix = multiply(matrix, parse_transform(element.attrib["transform"]))
    fill = element.attrib.get("fill", fill)
    if tag == "path":
        data = normalize_path(element.attrib["d"])
        prefix = "F0 " if element.attrib.get("fill-rule") == "evenodd" else "F1 "
        out.append((fill, prefix + data, matrix))
    for child in element:
        drawings(child, matrix, fill, out)


def drawing_image(key: str, svg: Path, recolor=None) -> list:
    root = ET.parse(svg).getroot()
    x, y, w, h = (float(v) for v in root.attrib["viewBox"].split())
    out = []
    drawings(root, (1, 0, 0, 1, -x, -y), "#000", out)
    lines = [f'  <DrawingImage x:Key="{key}">', "    <DrawingGroup>",
             f'      <GeometryDrawing Brush="Transparent" Geometry="M 0 0 H {fmt(w)} V {fmt(h)} H 0 Z"/>']
    for fill, data, m in out:
        color = (recolor or {}).get(fill.lower(), fill)
        identity = m == (1, 0, 0, 1, 0, 0)
        lines.append(f'      <GeometryDrawing Brush="{color}">')
        if identity:
            lines.append(f"        <GeometryDrawing.Geometry><StreamGeometry>{data}</StreamGeometry></GeometryDrawing.Geometry>")
        else:
            matrix = ",".join(fmt(v) for v in m)
            lines.append(f'        <GeometryDrawing.Geometry><PathGeometry Figures="{data}" Transform="matrix({matrix})"/></GeometryDrawing.Geometry>')
        lines.append("      </GeometryDrawing>")
    lines += ["    </DrawingGroup>", "  </DrawingImage>"]
    return lines


def main(source: str, target: str) -> None:
    src = Path(source)
    lines = [
        "<!-- Generated by eng/brand.py from assets/branding/*.svg. Edit the SVG sources, not this file. -->",
        '<ResourceDictionary xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">',
    ]
    lines += drawing_image("Brand.Mark", src / "mark.svg")
    lines += drawing_image("Brand.Lockup.Light", src / "lockup.svg")
    lines += drawing_image("Brand.Lockup.Dark", src / "lockup-dark.svg")
    lines.append("</ResourceDictionary>")
    Path(target).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(target)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
