#!/usr/bin/env python3
"""Convert pinned Lucide SVG icons into an Avalonia resource dictionary.

Usage: python3 eng/icons.py <directory-with-lucide-svgs> src/Jourfold.Desktop/Theme/Icons.axaml

Lucide icons are stroke drawings on a 24x24 grid. Every element is converted to
path data so the Icon control can stroke one geometry with the current foreground.
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

VERSION = "1.51.0"
NUMBER = re.compile(r"[-+]?(?:\d+\.\d*|\.\d+|\d+)(?:[eE][-+]?\d+)?")


def fmt(value: float) -> str:
    text = f"{value:.4f}".rstrip("0").rstrip(".")
    return "0" if text in ("-0", "") else text


def normalize_path(d: str) -> str:
    """Rewrite compact SVG path syntax into explicit, space-separated commands."""
    out = []
    i = 0
    command = None
    args_needed = {"M": 2, "L": 2, "H": 1, "V": 1, "C": 6, "S": 4, "Q": 4, "T": 2, "A": 7, "Z": 0}
    while i < len(d):
        ch = d[i]
        if ch.isspace() or ch == ",":
            i += 1
            continue
        if ch.isalpha():
            command = ch
            out.append(ch)
            i += 1
            if ch.upper() == "Z":
                command = None
            continue
        if command is None:
            raise ValueError(f"number without command in {d!r}")
        count = args_needed[command.upper()]
        values = []
        while len(values) < count:
            while i < len(d) and (d[i].isspace() or d[i] == ","):
                i += 1
            if command.upper() == "A" and len(values) in (3, 4):
                values.append(d[i])  # arc flags are single digits and may be packed
                i += 1
                continue
            match = NUMBER.match(d, i)
            if not match:
                raise ValueError(f"bad number at {d[i:i + 12]!r} in {d!r}")
            values.append(fmt(float(match.group())))
            i = match.end()
        if out and out[-1] != command:
            out.append(command)
        out.append(" ".join(values))
        if command == "M":
            command = "L"
        elif command == "m":
            command = "l"
    return " ".join(out)


def element_path(el) -> str:
    tag = el.tag.split("}")[-1]
    a = el.attrib
    f = lambda k, default=0.0: float(a.get(k, default))
    if tag == "path":
        d = a["d"].lstrip()
        # A path element's first moveto is absolute even when written as "m"; paths are concatenated here.
        if d.startswith("m"):
            d = "M0 0 " + d  # relative to the origin, so later implicit pairs stay relative
        return normalize_path(d)
    if tag == "circle":
        cx, cy, r = f("cx"), f("cy"), f("r")
        return f"M {fmt(cx - r)} {fmt(cy)} A {fmt(r)} {fmt(r)} 0 1 0 {fmt(cx + r)} {fmt(cy)} A {fmt(r)} {fmt(r)} 0 1 0 {fmt(cx - r)} {fmt(cy)} Z"
    if tag == "ellipse":
        cx, cy, rx, ry = f("cx"), f("cy"), f("rx"), f("ry")
        return f"M {fmt(cx - rx)} {fmt(cy)} A {fmt(rx)} {fmt(ry)} 0 1 0 {fmt(cx + rx)} {fmt(cy)} A {fmt(rx)} {fmt(ry)} 0 1 0 {fmt(cx - rx)} {fmt(cy)} Z"
    if tag == "line":
        return f"M {fmt(f('x1'))} {fmt(f('y1'))} L {fmt(f('x2'))} {fmt(f('y2'))}"
    if tag in ("polyline", "polygon"):
        points = [fmt(float(n)) for n in NUMBER.findall(a["points"])]
        pairs = [f"{points[i]} {points[i + 1]}" for i in range(0, len(points), 2)]
        return "M " + " L ".join(pairs) + (" Z" if tag == "polygon" else "")
    if tag == "rect":
        x, y, w, h = f("x"), f("y"), f("width"), f("height")
        rx = float(a.get("rx", a.get("ry", 0)))
        ry = float(a.get("ry", rx))
        if rx == 0:
            return f"M {fmt(x)} {fmt(y)} H {fmt(x + w)} V {fmt(y + h)} H {fmt(x)} Z"
        return (
            f"M {fmt(x + rx)} {fmt(y)} H {fmt(x + w - rx)} A {fmt(rx)} {fmt(ry)} 0 0 1 {fmt(x + w)} {fmt(y + ry)} "
            f"V {fmt(y + h - ry)} A {fmt(rx)} {fmt(ry)} 0 0 1 {fmt(x + w - rx)} {fmt(y + h)} H {fmt(x + rx)} "
            f"A {fmt(rx)} {fmt(ry)} 0 0 1 {fmt(x)} {fmt(y + h - ry)} V {fmt(y + ry)} A {fmt(rx)} {fmt(ry)} 0 0 1 {fmt(x + rx)} {fmt(y)} Z"
        )
    raise ValueError(f"unsupported element {tag}")


def main(source: str, target: str) -> None:
    entries = []
    for svg in sorted(Path(source).glob("*.svg")):
        root = ET.parse(svg).getroot()
        parts = [element_path(el) for el in root.iter() if el is not root and el.tag.split("}")[-1] != "title"]
        entries.append((svg.stem, " ".join(parts)))
    lines = [
        "<!-- Generated by eng/icons.py from lucide-static " + VERSION + " (ISC License, see licenses/lucide). Do not edit by hand. -->",
        '<ResourceDictionary xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">',
    ]
    for name, data in entries:
        lines.append(f'  <StreamGeometry x:Key="Icon.{name}">{data}</StreamGeometry>')
    lines.append("</ResourceDictionary>")
    Path(target).parent.mkdir(parents=True, exist_ok=True)
    Path(target).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(entries)} icons -> {target}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
