#!/usr/bin/env python3
"""One-off merge of the UI rebuild strings into Strings/en.json and Strings/de.json.

Each entry is key: (English, German). Existing keys are overwritten when listed here.
"""
import json
from pathlib import Path

S = {
    # Shell and navigation
    "Add": ("Add", "Hinzufügen"), "AddBudget": ("Budget", "Budget"), "AddPerson": ("Add person", "Person hinzufügen"),
    "PlanSection": ("Plan", "Planung"), "VersionsSection": ("Versions", "Versionen"), "TripMenu": ("Trip menu", "Reisemenü"),
    "SearchPlaceholder": ("Search…", "Suchen …"), "SearchTitle": ("Search and commands", "Suche und Befehle"),
    "InboxTip": ("Unscheduled ideas, notes and files (Ctrl+I)", "Ungeplante Ideen, Notizen und Dateien (Strg+I)"),
    "AllTrips": ("All trips", "Alle Reisen"), "TripDetails": ("Trip details", "Reisedetails"), "SaveACopy": ("Save a copy…", "Kopie speichern …"),
    "ShowInFolder": ("Show in folder", "Im Ordner anzeigen"), "CloseTrip": ("Close trip", "Reise schließen"), "More": ("More", "Mehr"),
    "Timetable": ("Timetable", "Zeitplan"), "Today": ("Today", "Heute"), "TodayTip": ("Jump to today", "Zu heute springen"),
    "ChooseDate": ("Choose a date", "Datum wählen"), "ByPerson": ("By person", "Nach Person"), "ByPersonTip": ("One column per traveller", "Eine Spalte pro Person"),
    "TimesIn": ("Times shown in {0}", "Zeiten in {0}"), "CurrentVariant": ("Current variant", "Aktuelle Variante"), "ManageVariants": ("Manage variants", "Varianten verwalten"),
    "Loading": ("Loading…", "Wird geladen …"), "SyncNow": ("Sync now", "Jetzt synchronisieren"), "LastSynced": ("Synced {0}", "Synchronisiert {0}"),
    "SyncLocalOnly": ("Only on this computer", "Nur auf diesem Computer"), "SyncLocalOnlyHint": ("Share to work together", "Zum Mitplanen teilen"),
    "SyncSynced": ("Synced", "Synchronisiert"), "SyncLocalChanges": ("Changes to upload", "Änderungen zum Hochladen"), "SyncRemoteChanges": ("New changes available", "Neue Änderungen verfügbar"),
    "SyncDiverged": ("Needs a merge", "Zusammenführung nötig"), "SyncFailed": ("Sync failed. Your local changes are safe.", "Synchronisierung fehlgeschlagen. Lokale Änderungen sind sicher."), "Syncing": ("Syncing…", "Wird synchronisiert …"),
    "Saving": ("Saving…", "Wird gespeichert …"), "NotInVersion": ("Not in a version yet", "Noch in keiner Version"), "SavedInVersion": ("All changes in a version", "Alles in einer Version"),
    "NotInVersionTip": ("Your edits are saved on this computer. Create a version to record them in the trip history.", "Ihre Änderungen sind auf diesem Computer gespeichert. Erstellen Sie eine Version, um sie in der Reisehistorie festzuhalten."),
    "SavedTip": ("Everything is saved and recorded in the trip history.", "Alles ist gespeichert und in der Reisehistorie festgehalten."),
    "VersionTip": ("Record the current state in the trip history (Ctrl+S)", "Aktuellen Stand in der Reisehistorie festhalten (Strg+S)"),
    "SampleTrip": ("Sample", "Beispiel"), "NoDatesYet": ("No dates yet", "Noch keine Daten"), "AddPeople": ("Add people", "Personen hinzufügen"),
    "Undone": ("Undone", "Rückgängig gemacht"), "Undo": ("Undo", "Rückgängig"), "Redo": ("Redo", "Wiederholen"),
    "DeletedItem": ("Deleted “{0}”", "„{0}“ gelöscht"), "CopyOf": ("{0} (copy)", "{0} (Kopie)"), "Duplicate": ("Duplicate", "Duplizieren"),
    "SomethingWentWrong": ("Something went wrong", "Etwas ist schiefgelaufen"), "NetworkError": ("The connection failed. Check your network and try again.", "Die Verbindung ist fehlgeschlagen. Prüfen Sie das Netzwerk und versuchen Sie es erneut."),
    "TripNeedsRepair": ("This trip needs a repair", "Diese Reise muss repariert werden"), "PleaseConfirm": ("Please confirm", "Bitte bestätigen"),
    "CannotOpen": ("No application is available to open this.", "Keine Anwendung zum Öffnen verfügbar."), "Filter": ("Filter", "Filtern"),
    "Choose": ("Choose…", "Auswählen …"), "ClearSelection": ("Clear", "Entfernen"), "SearchOrCreate": ("Search or type a new name", "Suchen oder neuen Namen eingeben"),
    "CreateNamed": ("Create “{0}”", "„{0}“ anlegen"), "SearchMapFor": ("Search the map for “{0}”", "Auf der Karte nach „{0}“ suchen"),
    "EnableOnlineSearchHint": ("Turn on online maps in Settings to search addresses.", "Aktivieren Sie Online-Karten in den Einstellungen, um Adressen zu suchen."),
    "NothingFound": ("Nothing found", "Nichts gefunden"), "Searching": ("Searching…", "Suche läuft …"), "OpenItem": ("Open {0}", "{0} öffnen"),
    "RemoveNamed": ("Remove {0}", "{0} entfernen"), "AddTo": ("Add to {0}", "Zu {0} hinzufügen"), "Copied": ("Copied to the clipboard", "In die Zwischenablage kopiert"),
    # Library
    "YourTrips": ("Your trips", "Ihre Reisen"), "LibraryHint": ("Each trip is a folder on this computer. Nothing is uploaded unless you share it.", "Jede Reise ist ein Ordner auf diesem Computer. Nichts wird hochgeladen, solange Sie nicht teilen."),
    "SearchTrips": ("Search trips", "Reisen suchen"), "Open": ("Open", "Öffnen"), "OnThisComputer": ("On this computer", "Auf diesem Computer"), "Shared": ("Shared", "Geteilt"),
    "OpenTripFolder": ("Open a trip folder", "Reiseordner öffnen"), "OpenTripFolderHint": ("A TravelRepo folder on this computer", "Ein TravelRepo-Ordner auf diesem Computer"),
    "Clone": ("Open from a link", "Über einen Link öffnen"), "CloneHint": ("A Git repository address someone shared with you", "Eine Git-Adresse, die jemand mit Ihnen geteilt hat"),
    "DiscoverGitHub": ("Find trips on GitHub", "Reisen auf GitHub finden"), "DiscoverGitHubHint": ("Trips in repositories you can access", "Reisen in Repositorys, auf die Sie Zugriff haben"),
    "ExploreSample": ("Explore a sample trip", "Beispielreise ansehen"), "ExploreSampleHint": ("A week in Japan to try everything out", "Eine Woche in Japan zum Ausprobieren"),
    "CreateFirstTrip": ("Plan a trip", "Reise planen"), "NewTripCardHint": ("Start with a title. Everything else can wait.", "Beginnen Sie mit einem Titel. Alles andere hat Zeit."),
    "WelcomeTitle": ("Plan trips together, at your own pace", "Reisen gemeinsam planen, im eigenen Tempo"),
    "WelcomeBody": ("Jourfold keeps every trip as an open folder on your computer. Try ideas as variants, record versions, and share when you are ready.", "Jourfold speichert jede Reise als offenen Ordner auf Ihrem Computer. Probieren Sie Ideen als Varianten aus, halten Sie Versionen fest und teilen Sie, wenn Sie bereit sind."),
    "WelcomeStep1": ("Plan days", "Tage planen"), "WelcomeStep1Body": ("Drag across the timetable to add activities, or collect ideas in the Inbox first.", "Ziehen Sie im Zeitplan, um Aktivitäten anzulegen, oder sammeln Sie Ideen zuerst im Eingang."),
    "WelcomeStep2": ("Try alternatives", "Alternativen ausprobieren"), "WelcomeStep2Body": ("Variants let you compare a cheaper or slower plan without losing the original.", "Mit Varianten vergleichen Sie einen günstigeren oder ruhigeren Plan, ohne das Original zu verlieren."),
    "WelcomeStep3": ("Share when ready", "Teilen, wenn es passt"), "WelcomeStep3Body": ("Publish privately to GitHub or your own Git server. It works offline too.", "Privat auf GitHub oder Ihrem eigenen Git-Server veröffentlichen. Es funktioniert auch offline."),
    "OpenedAgo": ("Opened {0}", "Geöffnet {0}"), "ItemsCount": ("{0} items", "{0} Einträge"), "FolderMissing": ("Folder not found", "Ordner nicht gefunden"), "LocateFolder": ("Find the folder…", "Ordner suchen …"),
    "RemoveFromList": ("Remove from this list", "Aus dieser Liste entfernen"), "NoTripsMatch": ("No trips match “{0}”.", "Keine Reise passt zu „{0}“."),
    "SampleCreated": ("Sample trip created. Feel free to change or delete it.", "Beispielreise erstellt. Sie können sie ändern oder löschen."),
    # New trip wizard
    "NewTrip": ("New trip", "Neue Reise"), "NewTripSubtitle": ("Only the title is needed. You can change everything later.", "Nur der Titel ist nötig. Alles andere lässt sich später ändern."),
    "TripTitle": ("Trip title", "Titel der Reise"), "TripTitleExample": ("For example: Lisbon in October", "Zum Beispiel: Lissabon im Oktober"),
    "DatesHint": ("Leave the dates empty if they are not fixed yet. Jourfold also derives dates from the plan.", "Lassen Sie die Daten leer, wenn sie noch offen sind. Jourfold leitet sie auch aus dem Plan ab."),
    "MainTimezone": ("Main timezone", "Hauptzeitzone"), "ContentLanguage": ("Language of trip notes", "Sprache der Reisenotizen"),
    "YourName": ("Your name", "Ihr Name"), "YourNameHint": ("Adds you as a traveller and signs your versions. Stored only in this trip and on this computer.", "Fügt Sie als reisende Person hinzu und kennzeichnet Ihre Versionen. Nur in dieser Reise und auf diesem Computer gespeichert."),
    "TravellingWith": ("Travelling with", "Mitreisende"), "CompanionName": ("Name of a companion", "Name einer mitreisenden Person"),
    "SavedAt": ("Saved in", "Gespeichert in"), "SavedAtHint": ("The trip is an ordinary folder with readable files and full version history.", "Die Reise ist ein normaler Ordner mit lesbaren Dateien und vollständiger Versionshistorie."),
    "ChangeFolder": ("Change…", "Ändern …"), "ConnectRemoteOptional": ("Connect an existing Git repository (optional)", "Vorhandenes Git-Repository verbinden (optional)"),
    "RemoteUrlOptional": ("https://… or git@…", "https://… oder git@…"), "WizardTrip": ("Trip", "Reise"), "WizardPeople": ("People", "Personen"), "WizardSave": ("Location", "Speicherort"),
    "Back": ("Back", "Zurück"), "Next": ("Next", "Weiter"), "CreateTrip": ("Create trip", "Reise erstellen"), "CreateNow": ("Create now", "Jetzt erstellen"),
    "TitleRequired": ("Enter a title.", "Bitte einen Titel eingeben."), "ChooseLocation": ("Choose a folder", "Ordner wählen"),
    # Quick add
    "AddToTrip": ("Add to trip", "Zur Reise hinzufügen"), "AtATime": ("At a specific time", "Zu einer bestimmten Uhrzeit"), "JustAnIdea": ("Just an idea for now", "Erst einmal nur eine Idee"),
    "StartTime": ("Start time", "Beginn"), "EndTime": ("End time", "Ende"), "StartDate": ("Start date", "Startdatum"), "EndDate": ("End date", "Enddatum"),
    "TransportMode": ("How", "Verkehrsmittel"), "From": ("From", "Von"), "To": ("To", "Nach"), "Where": ("Where", "Wo"), "Who": ("Who", "Wer"), "When": ("When", "Wann"),
    "Nights": ("Nights", "Nächte"), "CheckInDate": ("Check-in date", "Anreisedatum"), "BookingReferenceHint": ("Confirmation or booking number", "Bestätigungs- oder Buchungsnummer"),
    "PlaceWatermark": ("Type a place or pick one", "Ort eingeben oder auswählen"), "NoteWatermark": ("Write something. Markdown works.", "Schreiben Sie etwas. Markdown funktioniert."),
    "quick.activity": ("Activity", "Aktivität"), "quick.food": ("Food", "Essen"), "quick.sightseeing": ("Sight", "Besichtigung"), "quick.transport": ("Transport", "Fahrt"),
    "quick.accommodation": ("Stay", "Unterkunft"), "quick.booking": ("Booking", "Buchung"), "quick.task": ("Task", "Aufgabe"), "quick.note": ("Note", "Notiz"),
    "quick.place": ("Place", "Ort"), "quick.person": ("Person", "Person"), "quick.expense": ("Expense", "Ausgabe"), "quick.collection": ("Collection", "Sammlung"), "quick.budget": ("Budget", "Budget"),
    "placeholder.activity": ("What are you planning?", "Was haben Sie vor?"), "placeholder.food": ("Restaurant, café or market", "Restaurant, Café oder Markt"), "placeholder.sightseeing": ("Museum, viewpoint or landmark", "Museum, Aussichtspunkt oder Sehenswürdigkeit"),
    "placeholder.transport": ("Flight to Lisbon", "Flug nach Lissabon"), "placeholder.accommodation": ("Hotel, apartment or campsite", "Hotel, Wohnung oder Campingplatz"),
    "placeholder.booking": ("Flight tickets", "Flugtickets"), "placeholder.task": ("Renew passport", "Reisepass verlängern"), "placeholder.note": ("Packing list", "Packliste"),
    "placeholder.place": ("Name of the place", "Name des Ortes"), "placeholder.person": ("Name", "Name"), "placeholder.expense": ("Museum tickets", "Museumstickets"),
    "placeholder.collection": ("Restaurants to try", "Restaurants zum Ausprobieren"), "placeholder.budget": ("Food budget", "Essensbudget"),
    # Time
    "WhenTitle": ("When does it happen?", "Wann findet es statt?"), "ArrivesInOtherZone": ("Ends in another timezone", "Endet in einer anderen Zeitzone"),
    "hint.exact": ("A fixed start and end time.", "Feste Anfangs- und Endzeit."), "hint.approximate": ("Roughly at this time. Shown with a tilde.", "Ungefähr zu dieser Zeit. Mit Tilde angezeigt."),
    "hint.window": ("Some time between the earliest and latest time.", "Irgendwann zwischen frühester und spätester Zeit."), "hint.day_part": ("Morning, afternoon, evening or night of a day.", "Morgens, nachmittags, abends oder nachts an einem Tag."),
    "hint.all_day": ("The whole day.", "Der ganze Tag."), "hint.unscheduled": ("No time yet. The item stays in the Inbox.", "Noch keine Zeit. Der Eintrag bleibt im Eingang."),
    "FirstOccurrence": ("First time (before the clocks change back)", "Erstes Mal (vor der Zeitumstellung)"), "SecondOccurrence": ("Second time (after the clocks change back)", "Zweites Mal (nach der Zeitumstellung)"),
    "AllDay": ("All day", "Ganztägig"), "BetweenTimes": ("Between {0} and {1}", "Zwischen {0} und {1}"), "LocalTimeIn": ("{0} local time in {1}", "{0} Ortszeit {1}"), "ArrivesLocal": ("arrives {0} in {1}", "Ankunft {0} in {1}"),
    "DurationMinutesShort": ("{0} min", "{0} Min."), "DurationHoursShort": ("{0} h", "{0} Std."), "DurationHoursMinutesShort": ("{0} h {1} min", "{0} Std. {1} Min."), "MinutesShort": ("min", "Min."),
    "JustNow": ("just now", "gerade eben"), "MinutesAgo": ("{0} min ago", "vor {0} Min."), "HoursAgo": ("{0} h ago", "vor {0} Std."), "DaysAgo": ("{0} days ago", "vor {0} Tagen"),
    "EditTime": ("Change time", "Zeit ändern"), "MoveToInbox": ("Move to Inbox", "In den Eingang verschieben"), "NewActivityHere": ("New activity here", "Neue Aktivität hier"),
    "EmptyDaysTitle": ("Nothing planned on these days yet", "An diesen Tagen ist noch nichts geplant"), "EmptyDaysBody": ("Drag across the grid to add an activity, or drag an idea from the Inbox.", "Ziehen Sie im Raster, um eine Aktivität anzulegen, oder ziehen Sie eine Idee aus dem Eingang."),
    "DayN": ("Day {0}", "Tag {0}"), "NotScheduledYet": ("Not scheduled yet", "Noch nicht eingeplant"), "AddActivity": ("Add activity", "Aktivität hinzufügen"),
    "EmptyPlanTitle": ("Your plan is empty", "Ihr Plan ist leer"), "EmptyPlanBody": ("Add the first activity, transport or stay.", "Fügen Sie die erste Aktivität, Fahrt oder Unterkunft hinzu."),
    # Inbox
    "Inbox": ("Inbox", "Eingang"), "Pin": ("Keep open", "Geöffnet lassen"), "Unpin": ("Allow closing", "Schließen erlauben"), "All": ("All", "Alle"), "Ideas": ("Ideas", "Ideen"), "Notes": ("Notes", "Notizen"),
    "CaptureIdea": ("Add an idea and press Enter", "Idee eingeben und Enter drücken"), "InboxEmpty": ("Nothing here. Ideas without a time land here.", "Nichts hier. Ideen ohne Zeit landen hier."),
    "InboxDragHint": ("Drag onto the timetable to schedule", "Zum Einplanen auf den Zeitplan ziehen"), "Idea": ("Idea", "Idee"),
    # Inspector
    "CloseDetails": ("Close details", "Details schließen"), "Details": ("Details", "Details"), "Comments": ("Comments", "Kommentare"), "Comment": ("Comment", "Kommentieren"),
    "Journey": ("Journey", "Reiseweg"), "Stay": ("Stay", "Aufenthalt"), "InheritedFrom": ("Inherited from {0}", "Übernommen von {0}"), "UseParentPeople": ("Use the same people as the group", "Dieselben Personen wie die Gruppe verwenden"),
    "PartOf": ("Part of", "Teil von"), "AddSubItem": ("Add a step", "Schritt hinzufügen"), "NestedItems": ("Steps", "Schritte"), "TotalDuration": ("Total: {0}", "Gesamt: {0}"),
    "DerivedFromItems": ("Time comes from its steps.", "Die Zeit ergibt sich aus den Schritten."), "CommaSeparated": ("Separate with commas", "Mit Kommas trennen"),
    "AddConstraint": ("Add a rule", "Regel hinzufügen"), "ConstraintAfter": ("At least {0} after {1}", "Mindestens {0} nach {1}"), "ConstraintBefore": ("Arrive {0} before {1}", "{0} vor {1} ankommen"), "ConstraintEarliest": ("Not before {0}", "Nicht vor {0}"),
    "afterHint": ("Keep a gap after another item", "Abstand nach einem anderen Eintrag einhalten"), "earliest_startHint": ("Do not start before a time of day", "Nicht vor einer Uhrzeit beginnen"), "arrive_beforeHint": ("Be there before another item starts", "Vor Beginn eines anderen Eintrags da sein"),
    "UsedInSection": ("Used in", "Verwendet in"), "RawData": ("Stored data", "Gespeicherte Daten"), "Overview": ("Overview", "Überblick"), "Repository": ("Repository", "Repository"),
    "StatActivities": ("{0} activities", "{0} Aktivitäten"), "StatPlaces": ("{0} places", "{0} Orte"), "StatBookings": ("{0} bookings", "{0} Buchungen"), "StatTasks": ("{0} tasks", "{0} Aufgaben"), "StatFiles": ("{0} files", "{0} Dateien"),
    "UseAsCover": ("Use as trip cover", "Als Reisecover verwenden"), "Cover": ("Cover image", "Titelbild"), "SameFileElsewhere": ("The same file is stored once and used by {0} other entries.", "Dieselbe Datei ist einmal gespeichert und wird von {0} weiteren Einträgen genutzt."),
    "Location": ("Location", "Position"), "FindOnMap": ("Find address", "Adresse suchen"), "ShowOnMap": ("Show on map", "Auf der Karte zeigen"),
    "BookedItems": ("Booked items", "Gebuchte Einträge"), "EstimatedToggle": ("Estimated amount", "Geschätzter Betrag"), "Converted": ("Converted", "Umgerechnet"), "RateOn": ("rate {0} on {1}", "Kurs {0} am {1}"),
    "BudgetScope": ("Applies to", "Gilt für"), "trip": ("Trip", "Reise"), "category": ("Category", "Kategorie"), "participant": ("Person", "Person"),
    "You": ("You", "Sie"), "PersonLocalHint": ("People belong to this trip. There is no Jourfold account.", "Personen gehören zu dieser Reise. Es gibt kein Jourfold-Konto."),
    "GitIdentities": ("Email for versions", "E-Mail für Versionen"), "AddEmail": ("Add an email", "E-Mail hinzufügen"), "AddGitHubUser": ("Add a GitHub username", "GitHub-Benutzernamen hinzufügen"),
    "Avatar": ("Photo", "Foto"), "ThisIsMe": ("This is me", "Das bin ich"), "traveler": ("Traveller", "Reisende Person"), "organizer": ("Organiser", "Organisation"),
    "NoNotesYet": ("No notes yet.", "Noch keine Notizen."), "WriteNote": ("Write a note", "Notiz schreiben"), "AddNote": ("Add note", "Notiz hinzufügen"), "AddLink": ("Add link", "Link hinzufügen"),
    "AttachFile": ("Attach file", "Datei anhängen"), "MarkdownHint": ("Notes support Markdown: **bold**, lists and links.", "Notizen unterstützen Markdown: **fett**, Listen und Links."),
    "Note": ("Note", "Notiz"), "Preview": ("Preview", "Vorschau"), "NoCommentsYet": ("No comments yet.", "Noch keine Kommentare."), "WriteComment": ("Write a comment (Ctrl+Enter to send)", "Kommentar schreiben (Strg+Enter zum Senden)"),
    "CommentingAs": ("Commenting as {0}", "Kommentar als {0}"), "CommentAsHint": ("Add yourself to the trip to comment under your name.", "Fügen Sie sich der Reise hinzu, um unter Ihrem Namen zu kommentieren."),
    "Someone": ("Someone", "Jemand"), "AddComment": ("Add comment", "Kommentar hinzufügen"), "CommentNeedsPerson": ("Add a person to the trip before commenting.", "Fügen Sie vor dem Kommentieren eine Person zur Reise hinzu."),
    "field.title": ("Title", "Titel"), "field.name": ("Name", "Name"), "field.display_name": ("Name", "Name"), "field.status": ("Status", "Status"), "field.time": ("Time", "Zeit"),
    "field.participants": ("People", "Personen"), "field.transport": ("Transport", "Fahrt"), "field.accommodation": ("Stay", "Unterkunft"), "field.booking": ("Booking", "Buchung"),
    "field.default_place": ("Place", "Ort"), "field.category": ("Category", "Kategorie"), "field.tags": ("Tags", "Schlagwörter"), "field.content": ("Notes", "Notizen"),
    "field.children": ("Steps", "Schritte"), "field.constraints": ("Rules", "Regeln"), "field.amount": ("Amount", "Betrag"), "field.price": ("Price", "Preis"), "field.reference": ("Reference", "Referenz"),
    "field.location": ("Location", "Position"), "field.address": ("Address", "Adresse"), "field.dates": ("Dates", "Daten"), "field.cover": ("Cover", "Titelbild"), "field.duration": ("Duration", "Dauer"),
    "field.items": ("Items", "Einträge"), "field.travelers": ("Travellers", "Reisende"), "field.due": ("Due date", "Fällig"), "field.assigned_to": ("Assigned to", "Zuständig"), "field.body": ("Text", "Text"),
    "field.estimated": ("Estimated", "Geschätzt"), "field.paid_by": ("Paid by", "Bezahlt von"), "field.local": ("Local time", "Ortszeit"), "field.timezone": ("Timezone", "Zeitzone"), "field.start": ("Start", "Beginn"), "field.end": ("End", "Ende"),
    "WholeItem": ("Whole item", "Gesamter Eintrag"), "Empty": ("Empty", "Leer"),
    "kind.Activity": ("Activity", "Aktivität"), "kind.Transport": ("Transport", "Fahrt"), "kind.Accommodation": ("Stay", "Unterkunft"), "kind.Food": ("Food", "Essen"), "kind.Sightseeing": ("Sight", "Sehenswürdigkeit"),
    "kind.Culture": ("Culture", "Kultur"), "kind.Nature": ("Nature", "Natur"), "kind.Shopping": ("Shopping", "Einkaufen"), "kind.Nightlife": ("Nightlife", "Nachtleben"), "kind.Meeting": ("Meeting", "Treffen"), "kind.FreeTime": ("Free time", "Freizeit"), "kind.Other": ("Other", "Sonstiges"),
    "category.activity": ("Activity", "Aktivität"), "category.sightseeing": ("Sight", "Sehenswürdigkeit"), "category.food": ("Food", "Essen"), "category.culture": ("Culture", "Kultur"), "category.nature": ("Nature", "Natur"),
    "category.shopping": ("Shopping", "Einkaufen"), "category.nightlife": ("Nightlife", "Nachtleben"), "category.meeting": ("Meeting", "Treffen"), "category.free_time": ("Free time", "Freizeit"),
    "document": ("File", "Datei"), "schedule_item": ("Activity", "Aktivität"),
    # Collections
    "BookingsHint": ("Tickets, reservations and confirmations", "Tickets, Reservierungen und Bestätigungen"), "BookingsSummary": ("{0} bookings · {1} confirmed", "{0} Buchungen · {1} bestätigt"),
    "AddBooking": ("Add booking", "Buchung hinzufügen"), "NoBookingsTitle": ("No bookings yet", "Noch keine Buchungen"), "NoBookingsBody": ("Keep confirmation numbers, prices and documents together with the plan.", "Bewahren Sie Bestätigungsnummern, Preise und Dokumente beim Plan auf."),
    "CopyReference": ("Copy reference", "Referenz kopieren"), "NoDateYet": ("No date yet", "Noch kein Datum"),
    "CostsHint": ("Amounts stay in their own currency. Nothing is converted automatically.", "Beträge bleiben in ihrer Währung. Nichts wird automatisch umgerechnet."),
    "AddExpense": ("Add expense", "Ausgabe hinzufügen"), "NoCostsTitle": ("No costs yet", "Noch keine Kosten"), "NoCostsBody": ("Track what you spent and set a budget per currency.", "Erfassen Sie Ausgaben und legen Sie ein Budget pro Währung fest."),
    "OfBudget": ("of {0}", "von {0}"), "PaidAmount": ("{0} paid", "{0} bezahlt"), "EstimatedAmount": ("{0} estimated", "{0} geschätzt"), "BudgetLeft": ("{0} left", "Noch {0} übrig"), "BudgetOver": ("{0} over budget", "{0} über dem Budget"),
    "PaidBy": ("Paid by {0}", "Bezahlt von {0}"), "NoAutoConversion": ("Totals are per currency. Jourfold never rewrites amounts with current exchange rates.", "Summen gelten pro Währung. Jourfold rechnet Beträge nie mit aktuellen Kursen um."),
    "TasksHint": ("Things to do before and during the trip", "Was vor und während der Reise zu tun ist"), "AddTask": ("Add task", "Aufgabe hinzufügen"), "AddTaskPlaceholder": ("Add a task and press Enter", "Aufgabe eingeben und Enter drücken"),
    "ToDoCount": ("To do · {0}", "Offen · {0}"), "DoneCount": ("Done · {0}", "Erledigt · {0}"), "MarkDone": ("Mark “{0}” as done", "„{0}“ als erledigt markieren"), "NothingHere": ("Nothing here.", "Nichts hier."),
    "FilesHint": ("Tickets, documents, photos and notes", "Tickets, Dokumente, Fotos und Notizen"), "OptionalShort": ("Optional", "Optional"), "DropFilesTitle": ("Drop files here", "Dateien hier ablegen"), "DropFilesBody": ("Tickets, PDFs and photos are stored once inside the trip folder.", "Tickets, PDFs und Fotos werden einmal im Reiseordner gespeichert."),
    "UsedIn": ("used in {0}", "in {0} verwendet"), "AddFile": ("Add file", "Datei hinzufügen"), "FileAdded": ("Added “{0}”", "„{0}“ hinzugefügt"), "FilesAdded": ("Added {0} files", "{0} Dateien hinzugefügt"),
    "LargeFileNamed": ("“{0}” is larger than 25 MB and will make the trip history bigger. Add it anyway?", "„{0}“ ist größer als 25 MB und vergrößert die Reisehistorie. Trotzdem hinzufügen?"),
    "PeopleHint": ("Everyone travelling or helping to plan", "Alle, die mitreisen oder mitplanen"), "AddMyself": ("Add myself", "Mich hinzufügen"), "NoPeopleTitle": ("No people yet", "Noch keine Personen"),
    "NoPeopleBody": ("Add yourself and your travel companions to assign activities and tasks.", "Fügen Sie sich und Ihre Mitreisenden hinzu, um Aktivitäten und Aufgaben zuzuordnen."), "InItems": ("in {0} items", "in {0} Einträgen"),
    "PlacesHint": ("Where things happen", "Wo etwas stattfindet"), "PlacesSummary": ("{0} places", "{0} Orte"), "AddPlace": ("Add place", "Ort hinzufügen"), "NoPlacesTitle": ("No places yet", "Noch keine Orte"),
    "NoPlacesBody": ("Places appear on the map and connect activities, stays and transport.", "Orte erscheinen auf der Karte und verbinden Aktivitäten, Unterkünfte und Fahrten."), "NoLocationYet": ("No location yet", "Noch keine Position"), "NoLocation": ("No location", "Keine Position"),
    "CollectionsHint": ("Group places and ideas, like restaurants to try", "Orte und Ideen gruppieren, etwa Restaurants zum Ausprobieren"), "AddCollection": ("Add collection", "Sammlung hinzufügen"),
    "NoCollectionsTitle": ("No collections yet", "Noch keine Sammlungen"), "NoCollectionsBody": ("Collect beaches, museums or maybes without scheduling them.", "Sammeln Sie Strände, Museen oder Vielleichts, ohne sie einzuplanen."), "AndMore": ("and {0} more", "und {0} weitere"),
    # Map
    "FitMap": ("Show everything", "Alles zeigen"), "MapLayers": ("Map style", "Kartenstil"), "StreetMap": ("Street map (online)", "Straßenkarte (online)"),
    "ShowStreetMap": ("Show street map", "Straßenkarte zeigen"), "NotNow": ("Not now", "Nicht jetzt"), "StreetMapTitle": ("Show a street map?", "Straßenkarte anzeigen?"),
    "StreetMapBody": ("Map images come from OpenStreetMap. Only the map area you look at is sent to their server; your trip stays on this computer. You can change this in Settings.", "Die Kartenbilder kommen von OpenStreetMap. Nur der angezeigte Kartenausschnitt wird an deren Server gesendet; Ihre Reise bleibt auf diesem Computer. Sie können das in den Einstellungen ändern."),
    "MapEmptyTitle": ("No places on the map yet", "Noch keine Orte auf der Karte"), "MapEmptyBody": ("Add coordinates to a place, or turn on online maps to search addresses.", "Geben Sie einem Ort Koordinaten oder aktivieren Sie Online-Karten, um Adressen zu suchen."),
    "MapEmptyBodyOnline": ("Add a place and search its address to see it here.", "Fügen Sie einen Ort hinzu und suchen Sie seine Adresse, um ihn hier zu sehen."), "PlacesWithoutLocation": ("{0} places without a location", "{0} Orte ohne Position"),
    # Versions and history
    "Version": ("Create version", "Version erstellen"), "VersionSubtitle": ("Record the current plan in the trip history. Everyone who syncs sees this version.", "Halten Sie den aktuellen Plan in der Reisehistorie fest. Alle, die synchronisieren, sehen diese Version."),
    "Description": ("Description", "Beschreibung"), "VersionMessageHint": ("Suggested from your changes. Edit it freely.", "Aus Ihren Änderungen vorgeschlagen. Frei bearbeitbar."), "ChangesCount": ("Changes · {0}", "Änderungen · {0}"),
    "OnlyFormatChanges": ("Only file formatting changed.", "Nur die Dateiformatierung wurde geändert."), "NothingToVersion": ("Everything is already in a version.", "Alles ist bereits in einer Version."), "VersionCreated": ("Version created", "Version erstellt"),
    "VersionAdd": ("added {0}", "{0} hinzugefügt"), "VersionRemove": ("removed {0}", "{0} entfernt"), "VersionUpdate": ("updated {0}", "{0} aktualisiert"),
    "VersionAddMany": ("added {0} items", "{0} Einträge hinzugefügt"), "VersionUpdateMany": ("updated {0} items", "{0} Einträge aktualisiert"), "VersionRemoveMany": ("removed {0} items", "{0} Einträge entfernt"),
    "ListSeparator": (", ", ", "), "VersionSuggestion": ("Update the trip plan", "Reiseplan aktualisiert"),
    "ChangeAdded": ("Added {0} “{1}”", "{0} „{1}“ hinzugefügt"), "ChangeRemoved": ("Removed {0} “{1}”", "{0} „{1}“ entfernt"), "ChangeUpdated": ("Changed {0} “{1}”", "{0} „{1}“ geändert"),
    "HistoryHint": ("Every version of this trip, newest first. You can restore any of them.", "Alle Versionen dieser Reise, die neueste zuerst. Jede lässt sich wiederherstellen."),
    "HistoryVersionLine": ("{0} created a version", "{0} hat eine Version erstellt"), "HistoryCreateLine": ("{0} started the trip", "{0} hat die Reise begonnen"), "HistoryMergeLine": ("{0} merged a variant", "{0} hat eine Variante zusammengeführt"),
    "HistoryNewVariantLine": ("{0} created a variant", "{0} hat eine Variante erstellt"), "HistoryVariantLine": ("{0} updated a variant", "{0} hat eine Variante geändert"), "HistoryExternalLine": ("{0} changed the trip outside Jourfold", "{0} hat die Reise außerhalb von Jourfold geändert"),
    "ShowChanges": ("Show changes", "Änderungen zeigen"), "HideChanges": ("Hide changes", "Änderungen ausblenden"), "NoContentChanges": ("No content changes.", "Keine inhaltlichen Änderungen."),
    "Latest": ("Latest", "Neueste"), "Parents": ("Parents", "Vorgänger"), "RestoreThis": ("Restore this version", "Diese Version wiederherstellen"), "RestoreVersion": ("Restore version", "Version wiederherstellen"),
    "RestoreVersionBody": ("Bring back the plan from “{0}”? {1} files change. Your current state stays in the history, and you can undo the restore by restoring the latest version.", "Den Plan aus „{0}“ zurückholen? {1} Dateien ändern sich. Der aktuelle Stand bleibt in der Historie; Sie können durch Wiederherstellen der neuesten Version zurückkehren."),
    "Restore": ("Restore", "Wiederherstellen"), "Restored": ("Version restored. Create a version to keep it.", "Version wiederhergestellt. Erstellen Sie eine Version, um sie zu behalten."), "AlreadyThisVersion": ("The plan already matches this version.", "Der Plan entspricht bereits dieser Version."),
    "UnversionedChanges": ("Changes not in a version yet", "Änderungen noch in keiner Version"), "UnversionedChangesHint": ("They are saved on this computer. Create a version to add them to the history.", "Sie sind auf diesem Computer gespeichert. Erstellen Sie eine Version, um sie in die Historie aufzunehmen."),
    "UnversionedChangesBody": ("This needs your latest edits recorded as a version first. Jourfold can create it with a suggested description.", "Dafür müssen Ihre letzten Änderungen zuerst als Version festgehalten werden. Jourfold kann sie mit einer vorgeschlagenen Beschreibung erstellen."),
    "CreateVersionAndContinue": ("Create version and continue", "Version erstellen und fortfahren"),
    "VariantsHint": ("Alternative plans of the same trip. Compare them and merge the parts you like.", "Alternative Pläne derselben Reise. Vergleichen Sie sie und übernehmen Sie, was Ihnen gefällt."),
    "NewVariant": ("New variant", "Neue Variante"), "VariantTitle": ("Name of the variant", "Name der Variante"), "VariantHint": ("For example: Cheaper hotels", "Zum Beispiel: Günstigere Hotels"),
    "VariantCreated": ("Created “{0}”. You are now editing this variant.", "„{0}“ erstellt. Sie bearbeiten jetzt diese Variante."), "VariantNeedsVersion": ("A variant starts from a version. Create one from your current changes first?", "Eine Variante beginnt mit einer Version. Zuerst eine Version aus den aktuellen Änderungen erstellen?"),
    "SwitchedTo": ("Switched to “{0}”", "Zu „{0}“ gewechselt"), "YouAreHere": ("You are here", "Aktuell"), "MainPlan": ("Main plan", "Hauptplan"), "BasedOn": ("Based on {0}", "Basiert auf {0}"),
    "CreatedAgo": ("created {0}", "erstellt {0}"), "OnlineCopy": ("Online copy", "Online-Kopie"), "ArchivedHidden": ("{0} archived variants hidden. Turn on Advanced mode to see them.", "{0} archivierte Varianten ausgeblendet. Im erweiterten Modus sichtbar."),
    "VariantsExplainer": ("Create a variant to try a different plan without changing this one. Jourfold keeps both and helps you merge them later.", "Erstellen Sie eine Variante, um einen anderen Plan auszuprobieren, ohne diesen zu ändern. Jourfold behält beide und hilft beim späteren Zusammenführen."),
    "Switch": ("Switch to", "Wechseln"), "Compare": ("Compare", "Vergleichen"), "Merge": ("Merge into current", "In aktuellen Plan übernehmen"), "ShareVariant": ("Share", "Teilen"), "Archive": ("Archive", "Archivieren"), "Rename": ("Rename", "Umbenennen"),
    "ArchiveCurrent": ("Switch to another variant before archiving this one.", "Wechseln Sie zu einer anderen Variante, bevor Sie diese archivieren."),
    "MergeNoConflicts": ("Bring {1} changes from “{0}” into the current plan? Nothing conflicts.", "{1} Änderungen aus „{0}“ in den aktuellen Plan übernehmen? Es gibt keine Konflikte."),
    "MergedInto": ("Merged “{0}” into “{1}”", "„{0}“ in „{1}“ übernommen"), "MergedRemote": ("Merged the latest changes from your companions", "Neueste Änderungen der Mitreisenden übernommen"),
    "CompareTitle": ("{0} compared with {1}", "{0} im Vergleich mit {1}"), "NoScheduleToCompare": ("No scheduled items to compare", "Keine eingeplanten Einträge zum Vergleichen"),
    "PlansIdentical": ("The plans are identical", "Die Pläne sind identisch"), "PlansIdenticalBody": ("There is nothing to merge.", "Es gibt nichts zusammenzuführen."), "OnlyIn": ("Only in {0}", "Nur in {0}"),
    "ResolveConflicts": ("Choose what to keep", "Auswählen, was bleibt"), "ResolveConflictsBody": ("“{0}” and “{1}” changed the same details. Pick a result for each.", "„{0}“ und „{1}“ haben dieselben Details geändert. Wählen Sie jeweils ein Ergebnis."),
    "ConflictField": ("Changed: {0}", "Geändert: {0}"), "ConflictsResolved": ("{0} of {1} resolved", "{0} von {1} gelöst"), "ApplyMerge": ("Merge", "Zusammenführen"),
    "KeepFrom": ("Keep “{0}”", "„{0}“ behalten"), "TakeFrom": ("Take “{0}”", "„{0}“ übernehmen"), "KeepBoth": ("Keep both", "Beide behalten"), "KeepBothHint": ("Adds the other version as a separate copy", "Fügt die andere Fassung als eigene Kopie hinzu"),
    "EditResult": ("Write the result", "Ergebnis selbst festlegen"), "EditResultHint": ("Type the value to keep", "Den gewünschten Wert eingeben"), "CurrentPlan": ("Main plan", "Hauptplan"),
    # Sync and share
    "SyncNeedsVersion": ("You have changes that are not in a version yet. Only versions are shared. Create one now?", "Sie haben Änderungen, die noch in keiner Version sind. Geteilt werden nur Versionen. Jetzt eine erstellen?"),
    "CreateVersionAndSync": ("Create version and sync", "Version erstellen und synchronisieren"), "SyncedNow": ("Up to date", "Auf dem neuesten Stand"), "SyncedLocalChanges": ("Synced. Some local changes are not in a version yet.", "Synchronisiert. Einige lokale Änderungen sind noch in keiner Version."),
    "ThisComputer": ("This computer", "Dieser Computer"), "Publish": ("Share", "Teilen"), "Invite": ("Invite", "Einladen"), "Share": ("Share", "Teilen"),
    "ShareLocalSubtitle": ("This trip is only on this computer. Put it online to plan together.", "Diese Reise ist nur auf diesem Computer. Stellen Sie sie online, um gemeinsam zu planen."),
    "ShareRemoteSubtitle": ("Give companions access and send them a link.", "Geben Sie Mitreisenden Zugriff und schicken Sie ihnen einen Link."),
    "PublishToGitHub": ("Publish to GitHub", "Auf GitHub veröffentlichen"), "PublishToGitHubHint": ("Connects your GitHub account, then creates a private repository.", "Verbindet Ihr GitHub-Konto und erstellt dann ein privates Repository."),
    "PublishToGitHubConnected": ("Creates a private repository in your GitHub account.", "Erstellt ein privates Repository in Ihrem GitHub-Konto."),
    "RepositoryName": ("Repository name", "Repository-Name"), "PrivateByDefault": ("Private: only people you invite can see it.", "Privat: nur eingeladene Personen können es sehen."), "PublishPrivately": ("Publish privately", "Privat veröffentlichen"),
    "PublishedPrivately": ("Published privately as {0}", "Privat als {0} veröffentlicht"), "UseOwnGit": ("Use your own Git server", "Eigenen Git-Server verwenden"), "UseOwnGitHint": ("Gitea, GitLab, a NAS or any Git host over HTTPS or SSH.", "Gitea, GitLab, ein NAS oder jeder Git-Host über HTTPS oder SSH."),
    "ConnectAndUpload": ("Connect and upload", "Verbinden und hochladen"), "ShareExportHint": ("Or send a PDF or calendar file instead.", "Oder senden Sie stattdessen eine PDF- oder Kalenderdatei."),
    "InviteTitle": ("Invite on GitHub", "Auf GitHub einladen"), "InviteHint": ("They get access to {0}. They need a GitHub account.", "Die Person erhält Zugriff auf {0}. Sie benötigt ein GitHub-Konto."),
    "GitHubUsername": ("GitHub username", "GitHub-Benutzername"), "SendInvite": ("Send invite", "Einladung senden"), "Invited": ("Invited {0}", "{0} eingeladen"),
    "ShareLinkTitle": ("Send a link", "Link senden"), "CopyInvitation": ("Copy invitation", "Einladung kopieren"), "LinkCopied": ("Invitation copied", "Einladung kopiert"),
    "ShareMessage": ("Join me in planning “{0}” with Jourfold:\n{1}\n\nWithout Jourfold, clone {2} with Git.", "Plane „{0}“ mit mir in Jourfold:\n{1}\n\nOhne Jourfold: {2} mit Git klonen."),
    "ShareNotice": ("A link does not grant access. The person also needs permission on the server.", "Ein Link gewährt keinen Zugriff. Die Person braucht auch eine Berechtigung auf dem Server."),
    "RemoteAddedPushed": ("Connected and uploaded", "Verbunden und hochgeladen"), "RemoteAddedNotPushed": ("Connected. Uploading failed; Jourfold will try again when you sync.", "Verbunden. Das Hochladen ist fehlgeschlagen; Jourfold versucht es beim Synchronisieren erneut."),
    "RemoteName": ("Short name", "Kurzname"), "RemoteUrlHint": ("https://example.org/me/trip.git or git@example.org:me/trip.git", "https://example.org/ich/reise.git oder git@example.org:ich/reise.git"),
    "GitHubClientHint": ("From the GitHub App you registered for Jourfold. See the provider setup guide.", "Aus der GitHub-App, die Sie für Jourfold registriert haben. Siehe Anleitung zur Einrichtung."),
    "GitHubCodeBody": ("Your browser opened GitHub. Enter this code there; it is already copied:\n\n{0}\n\nClose this message when you have approved access.", "Ihr Browser hat GitHub geöffnet. Geben Sie dort diesen Code ein; er ist bereits kopiert:\n\n{0}\n\nSchließen Sie diese Meldung, sobald Sie den Zugriff bestätigt haben."),
    "GitHubConnected": ("GitHub connected", "GitHub verbunden"), "NoGitHubTrips": ("No trips were found in the repositories this app can access.", "In den freigegebenen Repositorys wurden keine Reisen gefunden."),
    "Private": ("Private", "Privat"), "Public": ("Public", "Öffentlich"),
    "PublicWarning": ("This repository is public. Anyone can see schedules, names, booking references, documents and photos in it.", "Dieses Repository ist öffentlich. Alle können Zeitpläne, Namen, Buchungsnummern, Dokumente und Fotos darin sehen."),
    "Exported": ("Exported {0}", "{0} exportiert"), "ShowFile": ("Show", "Anzeigen"), "PDFHint": ("A printable day-by-day plan", "Ein druckbarer Tagesplan"), "ICSHint": ("Import into your calendar app", "In die Kalender-App importieren"), "HTMLHint": ("A web page to print or share", "Eine Webseite zum Drucken oder Teilen"),
    "ExportTravellers": ("Travellers", "Reisende"), "ExportPaid": ("paid", "bezahlt"), "ExportEstimated": ("estimated", "geschätzt"), "ExportBudget": ("budget", "Budget"), "ExportRef": ("Ref.", "Ref."),
    "ExportFooter": ("Exported from Jourfold. The trip itself is an open TravelRepo folder.", "Aus Jourfold exportiert. Die Reise selbst ist ein offener TravelRepo-Ordner."),
    # Settings
    "LocalIdentity": ("You", "Sie"), "MapsAndPlaces": ("Maps and places", "Karten und Orte"), "Providers": ("Sharing", "Teilen"), "General": ("General", "Allgemein"), "Appearance": ("Appearance", "Darstellung"),
    "LanguageHint": ("Language of menus and labels. Trip content is never translated.", "Sprache der Menüs und Beschriftungen. Reiseinhalte werden nie übersetzt."),
    "OpenViewHint": ("What you see first when you open a trip", "Was Sie beim Öffnen einer Reise zuerst sehen"), "UnitsHint": ("Used for distances", "Für Entfernungen"),
    "TripsFolder": ("Folder for new trips", "Ordner für neue Reisen"), "TripsFolderHint": ("New trips and samples are created here unless you choose another folder.", "Neue Reisen und Beispiele werden hier angelegt, wenn Sie keinen anderen Ordner wählen."),
    "ThemeHint": ("System follows your desktop setting", "System folgt der Einstellung Ihres Desktops"), "DensityHint": ("Compact fits more on smaller screens", "Kompakt zeigt mehr auf kleineren Bildschirmen"),
    "TextSizeHint": ("Makes all text and controls larger", "Vergrößert alle Texte und Bedienelemente"), "HighContrastHint": ("Strong outlines and colours for better readability", "Kräftige Konturen und Farben für bessere Lesbarkeit"),
    "IdentityHint": ("Used when you add yourself to a trip and to sign the versions you create. It stays on this computer.", "Wird verwendet, wenn Sie sich einer Reise hinzufügen, und kennzeichnet Ihre Versionen. Bleibt auf diesem Computer."),
    "EmailOptional": ("Email (optional)", "E-Mail (optional)"), "EmailHint": ("Shown in version history so others can tell versions apart", "Erscheint in der Versionshistorie, damit andere Versionen zuordnen können"), "SavedIdentity": ("Saved", "Gespeichert"),
    "OnlineMaps": ("Online maps and address search", "Online-Karten und Adresssuche"), "OnlineMapsHint": ("Street maps and address search from OpenStreetMap", "Straßenkarten und Adresssuche von OpenStreetMap"),
    "OnlineMapsPrivacy": ("Off by default. When on, Jourfold loads map images for the area you view and sends address searches you start to OpenStreetMap. Trip data is never sent. Map images are cached on this computer.", "Standardmäßig aus. Wenn aktiv, lädt Jourfold Kartenbilder für den angezeigten Bereich und sendet von Ihnen gestartete Adresssuchen an OpenStreetMap. Reisedaten werden nie gesendet. Kartenbilder werden auf diesem Computer zwischengespeichert."),
    "ClearMapCache": ("Clear map cache", "Kartenspeicher leeren"), "ClearMapCacheHint": ("Remove stored map images", "Gespeicherte Kartenbilder entfernen"), "MapCacheCleared": ("Map cache cleared", "Kartenspeicher geleert"),
    "ProvidersHint": ("Connect accounts to publish and find trips. Generic Git over HTTPS and SSH works without an account here.", "Verbinden Sie Konten, um Reisen zu veröffentlichen und zu finden. Generisches Git über HTTPS und SSH funktioniert ohne Konto."),
    "GitHubConnectedHint": ("Connected on this computer", "Auf diesem Computer verbunden"), "GitHubNotConnected": ("Not connected", "Nicht verbunden"), "ConnectGitHub": ("Connect GitHub", "GitHub verbinden"),
    "PreferredRemoteHint": ("Where this trip syncs when it has several remotes", "Wohin diese Reise synchronisiert, wenn es mehrere Ziele gibt"),
    "PluginsHint": ("Plugins add new kinds of details. They run as separate programs you trust.", "Plugins fügen neue Arten von Details hinzu. Sie laufen als eigene Programme, denen Sie vertrauen."),
    "LoadPlugin": ("Load a plugin", "Plugin laden"), "NoPluginLoaded": ("No plugin loaded", "Kein Plugin geladen"), "ChoosePluginFolder": ("Choose plugin folder", "Plugin-Ordner wählen"), "PluginLoaded": ("Loaded plugin {0}", "Plugin {0} geladen"),
    "Plugins": ("Plugins", "Plugins"), "Advanced": ("Advanced mode", "Erweiterter Modus"), "AdvancedHint": ("Show branches, commits, remotes and stored data", "Zweige, Commits, Ziele und gespeicherte Daten anzeigen"),
    "DiagnosticsHint": ("Technical details for troubleshooting", "Technische Details zur Fehlersuche"), "Repair": ("Repair the trip", "Reise reparieren"), "RepairHint": ("Recover interrupted saves or restore the last version", "Unterbrochene Speichervorgänge wiederherstellen oder die letzte Version zurückholen"),
    "Report": ("Report a problem", "Problem melden"), "ReportHint": ("Prepare a report to copy. Nothing is sent automatically.", "Einen Bericht zum Kopieren vorbereiten. Es wird nichts automatisch gesendet."),
    "ReportTemplate": ("What happened:\n\nWhat I expected:\n\nSteps to reproduce:", "Was ist passiert:\n\nWas ich erwartet habe:\n\nSchritte zum Nachstellen:"), "ReportCopied": ("Report copied. Paste it where you report the issue.", "Bericht kopiert. Fügen Sie ihn dort ein, wo Sie das Problem melden."),
    "NothingToRepair": ("Nothing to repair. The trip matches its last version.", "Nichts zu reparieren. Die Reise entspricht ihrer letzten Version."),
    "TripFolder": ("Trip folder", "Reiseordner"), "Branch": ("Branch", "Zweig"), "GitStatus": ("Git status", "Git-Status"), "Commands": ("Commands", "Befehle"), "Navigation": ("Go to", "Gehe zu"),
    "GoTo": ("View", "Ansicht"), "InThisTrip": ("In this trip", "In dieser Reise"), "ToggleTheme": ("Switch light and dark", "Hell und dunkel wechseln"),
    "PaletteWatermark": ("Search the trip or type a command", "Reise durchsuchen oder Befehl eingeben"), "PaletteNavigate": ("to move", "zum Bewegen"), "PaletteOpen": ("to open", "zum Öffnen"),
    "QuickAdd": ("Add to trip", "Zur Reise hinzufügen"), "Settings": ("Settings", "Einstellungen"), "Close": ("Close", "Schließen"), "Save": ("Save", "Speichern"), "Cancel": ("Cancel", "Abbrechen"),
    "Continue": ("Continue", "Weiter"), "Remember": ("Last used view", "Zuletzt verwendet"), "Plan": ("Plan", "Plan"), "Map": ("Map", "Karte"), "List": ("List", "Liste"),
    "TripStart": ("Trip start", "Reisebeginn"), "Edit": ("Edit", "Bearbeiten"), "Remove": ("Remove", "Entfernen"), "RemoveContent": ("Remove", "Entfernen"),
    "Reference": ("Link to an item", "Mit Eintrag verknüpfen"), "Link": ("Address", "Adresse"), "OpenFile": ("Open", "Öffnen"), "Replace": ("Replace file", "Datei ersetzen"),
    "LargeFile": ("This file is larger than 25 MB and will increase trip history size. Add it?", "Diese Datei ist größer als 25 MB und vergrößert die Reisehistorie. Hinzufügen?"),
    "Rollback": ("Restore the last saved version? These files will change:", "Letzte gespeicherte Version wiederherstellen? Diese Dateien ändern sich:"),
    "PluginTrust": ("Plugins run as separate programs and can read the data Jourfold gives them. Only load plugins you trust.", "Plugins laufen als eigene Programme und können die Daten lesen, die Jourfold ihnen gibt. Laden Sie nur Plugins, denen Sie vertrauen."),
    "ExportFormat": ("Export the trip", "Reise exportieren"), "CloneLink": ("Copy this shared trip to your computer and open it?", "Diese geteilte Reise auf Ihren Computer kopieren und öffnen?"),
    "Unassigned": ("Nobody yet", "Noch niemand"), "Status": ("Status", "Status"), "Category": ("Category", "Kategorie"), "Tags": ("Tags", "Schlagwörter"), "Constraints": ("Planning rules", "Planungsregeln"),
    "Schedule": ("Schedule", "Einplanen"), "Booking": ("Booking", "Buchung"), "Place": ("Place", "Ort"), "Participants": ("People", "Personen"), "Items": ("Items", "Einträge"), "External": ("This trip changed outside Jourfold. Undo history was cleared to protect your changes.", "Diese Reise wurde außerhalb von Jourfold geändert. Der Rückgängig-Verlauf wurde gelöscht, um Ihre Änderungen zu schützen."),
    "Merged": ("Merged", "Zusammengeführt"), "Review": ("Review", "Prüfen"), "UseCurrent": ("Current plan", "Aktueller Plan"), "UseVariant": ("Other plan", "Anderer Plan"),
    "ScheduleComparison": ("Timetable", "Zeitplan"), "DetailsComparison": ("Changed details", "Geänderte Details"), "ChooseDay": ("Choose a day", "Tag wählen"),
    "Added": ("Added", "Neu"), "Removed": ("Removed", "Entfernt"), "ChangedDetails": ("Changed", "Geändert"),
    "MergeNotice": ("Your companions' changes fit with yours. Merging in 10 seconds unless you review or cancel.", "Die Änderungen der Mitreisenden passen zu Ihren. Zusammenführung in 10 Sekunden, außer Sie prüfen oder brechen ab."),
    "SyncConflict": ("The shared plan needs a decision. Use Sync to review the differences.", "Der geteilte Plan braucht eine Entscheidung. Mit Synchronisieren die Unterschiede prüfen."),
    "Sync": ("Sync", "Synchronisieren"), "Remote": ("Remote", "Ziel"), "RemoteUrl": ("Repository address", "Repository-Adresse"), "AddRemote": ("Add a Git remote", "Git-Ziel hinzufügen"),
}

def main():
    root = Path(__file__).resolve().parent.parent / "src" / "Jourfold.Desktop" / "Strings"
    for index, name in ((0, "en"), (1, "de")):
        path = root / f"{name}.json"
        data = json.loads(path.read_text(encoding="utf-8"))
        for key, values in S.items():
            data[key] = values[index]
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(path, len(data))

if __name__ == "__main__":
    main()
