<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression><OutputType>Exe</OutputType></PropertyGroup><ItemGroup><ProjectReference Include="../../../travelrepo/src/TravelRepo.Plugins.Abstractions/TravelRepo.Plugins.Abstractions.csproj" Condition="Exists('../../../travelrepo/src/TravelRepo.Plugins.Abstractions/TravelRepo.Plugins.Abstractions.csproj')"/><PackageReference Include="TravelRepo.Plugins.Abstractions" Version="$(TravelRepoVersion)" Condition="!Exists('../../../travelrepo/src/TravelRepo.Plugins.Abstractions/TravelRepo.Plugins.Abstractions.csproj')"/></ItemGroup></Project>
